# Generated by Django 4.1.2 on 2022-11-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='mail',
            field=models.TextField(blank=True, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='todo',
            name='password',
            field=models.TextField(blank=True, verbose_name='パスワード'),
        ),
    ]
