# Generated by Django 4.1.3 on 2022-11-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_mail_todo_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='password',
        ),
    ]
