# Generated by Django 4.1.3 on 2022-11-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_create_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='create_user',
        ),
        migrations.AddField(
            model_name='todo',
            name='mail',
            field=models.TextField(blank=True, verbose_name='メール'),
        ),
    ]
