# Generated by Django 4.1.3 on 2022-11-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_todo_create_user_todo_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='frequency',
            field=models.IntegerField(blank=True, default=24, verbose_name='通知の送信時間間隔'),
        ),
    ]
